### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by mbardelmeijer** [CyberfusionNL/cyberfusion-cluster-api-client#46]
## Goal

When installing the package with Laravel 10, a conflict arises:

```
Root composer.json requires cyberfusion/cluster-api-client ^1.91.0 -> satisfiable by cyberfusion/cluster-api-client[v1.91.0, v1.91.1].
    - Conclusion: don't install laravel/framework v10.2.0 (conflict analysis result)
    - cyberfusion/cluster-api-client[v1.91.0, ..., v1.91.1] require illuminate/support ^8.22 || ^9.0 -> satisfiable by illuminate/support[v8.22.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev].
```

## Additional information

Allowing `illuminate/support` ^10.0 in `composer.json` should do the trick! https://github.com/CyberfusionNL/cyberfusion-cluster-api-client/blob/main/composer.json#L15

**Comment by dvdheiden** [comment]
https://github.com/CyberfusionNL/cyberfusion-cluster-api-client/releases/tag/v1.92.0

**Comment by mbardelmeijer** [comment]
That's quick! Thanks 🙏
